module.exports = {
  '/privacy': ['/privatsphare'],
  '/about': ['/uber'],
  '/checkout': ['/auschecken'],
  '/email-verified': ['/email-uberpruft'],
  '/imprint': ['/impressum'],
  '/login': ['/anmeldung'],
  '/logout': ['/ausloggen'],
  '/register': ['/registrieren'],
  '/reset-password': ['/passwort-zurucksetzen'],
  '/review': ['/rezension'],
  '/sign-up': ['/anmelden'],
  '/thank-you': ['/danke'],
  '/shop/:slug*': ['/geschaft/:slug*'],
  '/shop': ['/geschaft'],
  '/product': ['/produkt'],
  '/product/:slug': ['/produkt/:slug'],
  '/order/:id': ['/auftrag/:id'],
  '/order': ['/auftrag'],
  '/account': ['/konto'],
  '/account/change-password': ['/konto/kennwort-andern'],
  '/account/forget-password': ['/konto/passwort-vergessen'],
};
